name: tests

on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: |      
          npm ci
    - run: |
        npm i
        chmod -R a+x node_modules
        npm install cucumber-html-reporter --save-dev
        npm test
        ls -ls
        ls -ls report
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: cucumber-report.json
