name: tests

on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: |      
          npm i
          chmod -R a+x node_modules
          mkdir reports
    - name: reporter
      run: |        
        #npm install cucumber-html-reporter --save-dev
        npm install multiple-cucumber-html-reporter --save-dev
        npm test
        #npm run test:report
        npm run test:reportm
        cp reports/report.json reports/html/.
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      if: ${{ always() }}
      with:
        access-token: ${{ secrets.GH_TOKEN }}
        path: "reports/report.json"
    - name: generate table
      run: |    
        SUMMARY=$(cat << EOF
        ##### **Scenario** Greeting 
        Total: 4 | passed: 2 | failed: 5
        | step | keyword | status | location |
        | ------ | ------ | ------ | ------ |
        | the greeter says hello | When | :heavy_check_mark: passed | features/step_definitions/steps.ts:10 |
        | I should have heard "hell" | Then | :negative_squared_cross_mark: failed | features/step_definitions/steps.ts:14 |
        ##### **Scenario** Saludar 
        | step | keyword | status | location |
        | ------ | ------ | ------ | ------ |
        | the greeter says hello | When | :heavy_check_mark: passed | features/step_definitions/steps.ts:10 |
        | I should have heard "hell" | Then | :heavy_check_mark: passed | features/step_definitions/steps.ts:14 |
        EOF
        )
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/html
