name: tests

on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: |      
          npm i
          chmod -R a+x node_modules
          mkdir reports
    - name: reporter
      run: |        
        #npm install cucumber-html-reporter --save-dev
        npm install multiple-cucumber-html-reporter --save-dev
        npm test | tee 
        #npm run test:report
        npm run test:reportm
        cp reports/report.json reports/html/.
    - name: generate table
      run: |    
        SUMMARY=$(cat << EOF
        | Command | Description |
        | --- | --- |
        | git status | List all new or modified files |
        | git diff | Show file differences that haven't been staged |
        EOF
        )
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/html
