name: tests

on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: |      
          npm i
          chmod -R a+x node_modules
          mkdir reports
          npx playwright install --with-deps
    - name: reporter
      run: |        
        #npm install cucumber-html-reporter --save-dev
        npm install multiple-cucumber-html-reporter --save-dev
        npm test        
        #npm run test:report
        #npm run test:reportm
        cp reports/report.json reports/html/.
    - name: "read report"
      if: ${{ always() }}
      run: |
        more reports/report.json
        npm run test:reportm        
    - name: generate table1
      if: ${{ always() }}
      run: |   
        sh createtable.sh
        #SUMMARY=$(<createtable.sh)
        #echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: reports
        path: reports/html
